### ISSUE TITLE
libsndfile 1.1.0 release

### ISSUE THREAD

**Issue by tgarc** [bastibe/libsndfile-binaries#10]
There's been a major release of libsndfile with mp3 support and a bunch of bug fixes:

https://github.com/libsndfile/libsndfile/releases/tag/1.1.0

Is it difficult to update to this version? Anything I can help with?

**Comment by bastibe** [comment]
I think the code in python-soundfile itself is easy to change, and there's already a pull request under way to add the required definitions for libsndfile 1.1.0. 

The hard part will be rebuilding libsndfile for windows 32/64 and macOS 64/arm (and maybe Linux 64, if anyone can figure out a reliable way of doing so). I'll try to work on that next week, but I'd be grateful for any help on this, either with manually compiled binaries, or with the appropriate changes to our CI build scripts.

**Comment by tgarc** [comment]
Are you referring to this PR: https://github.com/bastibe/python-soundfile/pull/335

**Comment by bastibe** [comment]
yes, that's the one.
