### ISSUE TITLE
libsndfile 1.2.0

### ISSUE THREAD

**Issue by dofuuz** [bastibe/libsndfile-binaries#19]
https://github.com/libsndfile/libsndfile/releases

New upstream update is available!

**Comment by bastibe** [comment]
Good to know, thank you! I'll try to cut a new release of soundfile in the beginning of next year, as time allows. 

If you'd like to check/correct my build scripts in the meantime, that would help tremendously!

**Comment by bastibe** [comment]
Work on this is now ongoing in https://github.com/bastibe/libsndfile-binaries/pull/20
