### ISSUE TITLE
Update libsndfile to 1.0.30

### ISSUE THREAD

**Issue by tchagnon** [bastibe/libsndfile-binaries#3]
libsndfile 1.0.30 was released on Sep 19, 2020. Could you updated to include the latest release of the lib? There are a number of bugfixes and improvements.
https://github.com/libsndfile/libsndfile/tags

In particular, I'd like to pick up this fix for slow sf_seek().
libsndfile/libsndfile#491

PySoundfile depends on these binaries as a submodule:
https://github.com/bastibe/SoundFile

**Comment by mgeier** [comment]
Thanks for opening this issue!

I've just created a PR for `mxe`: https://github.com/mxe/mxe/pull/2587.
As soon as that is merged, I can create the DLLs for Windows.

I currently don't have access to a Mac, so I can't create the `.dylib`.
I hope somebody else can provide a PR for that (please note the added `opus` dependency!).

**Comment by tchagnon** [comment]
I could provide the `.dylib` for mac.  Do you think the instructions in the README are up to date?  I can look into it.

**Comment by mgeier** [comment]
> I could provide the `.dylib` for mac.

That would be great!

> Do you think the instructions in the README are up to date?

The `libsndfile` download location has changed to https://github.com/libsndfile/libsndfile/releases/download/v1.0.30/libsndfile-1.0.30.tar.bz2.

There is now an additional dependency to the opus library.

And I think those version can be updated:

```
flac-1.3.3
libogg-1.3.4
libvorbis-1.3.7
```

Other than that, I think it is up to date.

**Comment by tchagnon** [comment]
I figured it out.  The Flac build was failing due to some bad uint types in the ogg headers.  I was also able to test that it's working in the `SoundFile` repo with `python setup.py test` while pointed at my local branch here.
