### ISSUE TITLE
libsndfile DLLs with MP3 support?

### ISSUE THREAD

**Issue by xtingray** [bastibe/libsndfile-binaries#6]
Hello there,

I am looking for the DLL files of the latest **libsndfile** version, including **MP3 support.** I wonder if you could build them. I tried to do it following the instructions described in the README.md with no luck.

I appreciate any help. Thanks!

**Comment by tgarc** [comment]
> Hello there,
> 
> I am looking for the DLL files of the latest **libsndfile** version, including **MP3 support.** I wonder if you could build them. I tried to do it following the instructions described in the README.md with no luck.
> 
> I appreciate any help. Thanks!

Mp3 support has been released:
https://github.com/libsndfile/libsndfile/releases/tag/1.1.0
